version: '3.7'

services:
  mysql-master:
    image: mysql:8.0.36
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    command: >
      --server-id=1 --log-bin=mysql-bin --binlog-do-db=testdb
    volumes:
      - master-data:/var/lib/mysql
    networks:
      - mysql-net

  mysql-slave:
    image: mysql:8.0.36
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    command: >
      --server-id=2 --relay-log=relay-bin --log-bin=mysql-bin --read-only=1
    volumes:
      - slave-data:/var/lib/mysql
    depends_on:
      - mysql-master
    networks:
      - mysql-net

volumes:
  master-data:
  slave-data:

networks:
  mysql-net:
    driver: bridge
